/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import java.io.File;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author patrick DUPRE
 */
public class AuSujet extends javax.swing.JFrame {

	
	/**
	 * Creates new form NewJFrame
	 */
	public AuSujet() {
		initComponents();
		String Text_About = "<html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
		Text_About += "<style>body {  background-color: white;  margin-top: 2px;}";
		Text_About += "img {  border:  none;  margin: 2px;  vertical-align: top;}";
		Text_About += "table {  border-style: none;  border-width: 0px;  border: 0px;  margin: 0px;  padding: 0px;";
		Text_About += "  border-collapse: collapse;  background-image: none;  width: 100%;  top: 0px;  right: 0px;  bottom: 0px;";
		Text_About += "  left: 0px;  vertical-align: top;    color: navy;  font-size: 12px;  font-family: Verdana;}";
		Text_About += "</style>";
		Text_About += "</head><body bgcolor=\"white\"><div><table width=\"380\"><tr><td align=\"center\">";
		Text_About += "<IMG SRC=\"http://www.st2msi.net/img/btssiolcn_150.png\" alt=\"Image\"></td></tr>";
		Text_About += "<tr><td align=\"center\">Gestion des utilisateurs et ressources en Java";
		Text_About += "<h2>BTS SIO SLAM</h2><a href=\"http://www.st2msi.net\">Lycée Claude Nouga - 82300 MONTEILS</a></td>";
		Text_About += "</tr></table></div></body></html>";
		/*String HTMLdata = "";
		int tmp;
		ClassLoader classLoader = getClass().getClassLoader();
		try {
			File fichierHTML = new File(classLoader.getResource("../ressource/about.html").getFile());
			FileReader myReader = new FileReader(fichierHTML);
			try {
				while ((tmp = myReader.read()) != -1) {
					HTMLdata += (char) tmp;
				}
			} catch (IOException ex) {
				Logger.getLogger(AuSujet.class.getName()).log(Level.SEVERE, null, ex);
			}
			try {
				myReader.close();
			} catch (IOException ex) {
				Logger.getLogger(AuSujet.class.getName()).log(Level.SEVERE, null, ex);
			}
		} catch (FileNotFoundException ex) {
			Logger.getLogger(AuSujet.class.getName()).log(Level.SEVERE, null, ex);
		}*/
		HTML_Panel.setText(Text_About);

		//HTML_Panel.setText(Text_About);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                HTML_Panel = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                HTML_Panel.setText("HTML");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(HTML_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(HTML_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AuSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AuSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AuSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AuSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AuSujet().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel HTML_Panel;
        // End of variables declaration//GEN-END:variables
}
