/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import java.security.SecureRandom;
import org.springframework.security.crypto.bcrypt.*;

/**
 *
 * @author Patrick DUPRE
 */
public class Crud extends javax.swing.JFrame {

	/**
	 * Creates new form Crud
	 */
	Connection con;
	Statement st;
	ArrayList<Utilisateur> lesUtilisateurs = new ArrayList<>();

	public Crud() {
		initComponents();
		Entete.setBackground(new java.awt.Color(0, 128, 255, 30));
		message.setBackground(new java.awt.Color(255, 255, 255, 50));
		tbScrollPane.getViewport().setBackground(new java.awt.Color(255, 255, 255, 100));
		jPanelSaisie.setBackground(new java.awt.Color(255, 255, 255, 80));
		jPanelBt.setBackground(new java.awt.Color(255, 255, 255, 100));
		message.setForeground(new java.awt.Color(51, 102, 0));
		message.setText("Veuillez choisir un utilisateur dans le tableau de droite ou saisir les données à creer");

		chargerLesUtilisateurs();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                Entete = new javax.swing.JLabel();
                tbScrollPane = new javax.swing.JScrollPane();
                tbUtilisateur = new javax.swing.JTable();
                jPanelSaisie = new javax.swing.JPanel();
                jLabelNom = new javax.swing.JLabel();
                uiNom = new javax.swing.JTextField();
                jLabelPrenom = new javax.swing.JLabel();
                uiPrenom = new javax.swing.JTextField();
                jLabelPseudo = new javax.swing.JLabel();
                uiPseudo = new javax.swing.JTextField();
                jLabelMail = new javax.swing.JLabel();
                uiMail = new javax.swing.JTextField();
                jLabelMP = new javax.swing.JLabel();
                uiMP = new javax.swing.JTextField();
                uiPhrase = new javax.swing.JLabel();
                Vider = new javax.swing.JButton();
                Creer = new javax.swing.JButton();
                Modifier = new javax.swing.JButton();
                Supprimer = new javax.swing.JButton();
                message = new javax.swing.JLabel();
                jPanelBt = new javax.swing.JPanel();
                Parametre = new javax.swing.JButton();
                Mailer = new javax.swing.JButton();
                Aide = new javax.swing.JButton();
                AuSujet = new javax.swing.JButton();
                Quitter = new javax.swing.JButton();
                uiBackground = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("CRUD");
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                setMaximumSize(new java.awt.Dimension(1024, 640));
                setMinimumSize(new java.awt.Dimension(1024, 640));
                setPreferredSize(new java.awt.Dimension(1024, 640));
                setResizable(false);
                setSize(new java.awt.Dimension(1024, 640));
                getContentPane().setLayout(null);

                Entete.setBackground(new java.awt.Color(0,128,255,30));
                Entete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
                Entete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/java_64.png"))); // NOI18N
                Entete.setText("CRUD SIMPLIFIE : GESTION DES UTILISATEURS ET AUTRES RESSOURCES");
                Entete.setMaximumSize(new java.awt.Dimension(1024, 70));
                Entete.setMinimumSize(new java.awt.Dimension(1024, 70));
                Entete.setOpaque(true);
                Entete.setPreferredSize(new java.awt.Dimension(1024, 70));
                getContentPane().add(Entete);
                Entete.setBounds(0, 0, 1024, 70);

                tbScrollPane.setBackground(new java.awt.Color(255, 255, 255));
                tbScrollPane.setOpaque(false);

                tbUtilisateur.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Nom", "Prénom", "Utilisateur"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tbUtilisateur.setOpaque(false);
                tbUtilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tbUtilisateurMouseClicked(evt);
                        }
                });
                tbScrollPane.setViewportView(tbUtilisateur);
                if (tbUtilisateur.getColumnModel().getColumnCount() > 0) {
                        tbUtilisateur.getColumnModel().getColumn(2).setResizable(false);
                }

                getContentPane().add(tbScrollPane);
                tbScrollPane.setBounds(12, 77, 439, 410);

                jPanelSaisie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jPanelSaisie.setOpaque(false);

                jLabelNom.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabelNom.setText("Nom");

                jLabelPrenom.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabelPrenom.setText("Prénom");

                jLabelPseudo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabelPseudo.setText("Utilisateur");

                jLabelMail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabelMail.setText("Mail");

                jLabelMP.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabelMP.setText("Mot passe");

                uiMP.addCaretListener(new javax.swing.event.CaretListener() {
                        public void caretUpdate(javax.swing.event.CaretEvent evt) {
                                uiMPCaretUpdate(evt);
                        }
                });

                uiPhrase.setBackground(new java.awt.Color(255, 255, 255));
                uiPhrase.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                uiPhrase.setForeground(new java.awt.Color(204, 0, 51));

                Vider.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                Vider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/eye-slash_20.png"))); // NOI18N
                Vider.setText("Nouveau");
                Vider.setToolTipText("Dé-selectionner l'utilisateur");
                Vider.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                ViderMouseClicked(evt);
                        }
                });

                Creer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                Creer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/plus_20.png"))); // NOI18N
                Creer.setText("Creer");
                Creer.setToolTipText("Valider la création d'un nouvel utilisateur");
                Creer.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                CreerMouseClicked(evt);
                        }
                });

                Modifier.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                Modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/pencil_20.png"))); // NOI18N
                Modifier.setText("Modifier");
                Modifier.setToolTipText("Valider les modifications");
                Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                ModifierMouseClicked(evt);
                        }
                });

                Supprimer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                Supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/minus_20.png"))); // NOI18N
                Supprimer.setText("Supprimer");
                Supprimer.setToolTipText("Supprimer l'utilisateur");

                javax.swing.GroupLayout jPanelSaisieLayout = new javax.swing.GroupLayout(jPanelSaisie);
                jPanelSaisie.setLayout(jPanelSaisieLayout);
                jPanelSaisieLayout.setHorizontalGroup(
                        jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                                .addComponent(jLabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(uiMail))
                                        .addComponent(uiPhrase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabelNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabelPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabelPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(uiPrenom)
                                                                        .addComponent(uiPseudo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                                                        .addComponent(uiNom)))
                                                        .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                                                .addComponent(jLabelMP, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(uiMP, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSaisieLayout.createSequentialGroup()
                                                .addComponent(Creer)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Modifier)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Supprimer)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                                .addComponent(Vider)))
                                .addContainerGap())
                );
                jPanelSaisieLayout.setVerticalGroup(
                        jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(uiNom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(uiPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(uiPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(uiMail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(uiMP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelMP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Vider)
                                        .addComponent(Creer)
                                        .addComponent(Modifier)
                                        .addComponent(Supprimer))
                                .addContainerGap())
                );

                getContentPane().add(jPanelSaisie);
                jPanelSaisie.setBounds(469, 77, 540, 410);

                message.setBackground(new java.awt.Color(255, 255, 255));
                message.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                message.setForeground(new java.awt.Color(51, 102, 0));
                message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                message.setText("Message");
                getContentPane().add(message);
                message.setBounds(20, 510, 990, 17);

                jPanelBt.setBackground(new java.awt.Color(255, 255, 255));
                jPanelBt.setMaximumSize(new java.awt.Dimension(1024, 50));
                jPanelBt.setMinimumSize(new java.awt.Dimension(1024, 50));
                jPanelBt.setPreferredSize(new java.awt.Dimension(1010, 50));

                Parametre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                Parametre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/wrench._20.png"))); // NOI18N
                Parametre.setText("Paramètre");
                Parametre.setToolTipText("Paramètres de l'application");
                Parametre.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                ParametreMouseClicked(evt);
                        }
                });

                Mailer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                Mailer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/envelope_20.png"))); // NOI18N
                Mailer.setText("Mail");
                Mailer.setToolTipText("Envoyer un mail à l'utilisateur");
                Mailer.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                MailerMouseClicked(evt);
                        }
                });

                Aide.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                Aide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/question-circle_20.png"))); // NOI18N
                Aide.setText("Aide");
                Aide.setToolTipText("Manuel utilisateur");
                Aide.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                AideMouseClicked(evt);
                        }
                });

                AuSujet.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                AuSujet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/info-circle_20.png"))); // NOI18N
                AuSujet.setText("Au sujet");
                AuSujet.setToolTipText("Au sujet de l'application");
                AuSujet.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                AuSujetMouseClicked(evt);
                        }
                });

                Quitter.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/escape_20.png"))); // NOI18N
                Quitter.setText("Quitter");
                Quitter.setToolTipText("Quitter l'application");
                Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                QuitterMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanelBtLayout = new javax.swing.GroupLayout(jPanelBt);
                jPanelBt.setLayout(jPanelBtLayout);
                jPanelBtLayout.setHorizontalGroup(
                        jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtLayout.createSequentialGroup()
                                .addComponent(Parametre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
                                .addComponent(Mailer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AuSujet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Aide)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Quitter))
                );
                jPanelBtLayout.setVerticalGroup(
                        jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelBtLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Quitter)
                                                .addComponent(Aide))
                                        .addGroup(jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(AuSujet)
                                                .addComponent(Mailer)
                                                .addComponent(Parametre)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                getContentPane().add(jPanelBt);
                jPanelBt.setBounds(10, 550, 1010, 50);

                uiBackground.setBackground(new java.awt.Color(255, 255, 255));
                uiBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/back_ec.jpg"))); // NOI18N
                getContentPane().add(uiBackground);
                uiBackground.setBounds(0, 0, 1024, 640);

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

	// Positionner les valeurs de la zone de texte 
    private void tbUtilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUtilisateurMouseClicked
	    // TODO add your handling code here:
	    // pointer sur le colonne selectionnée
	    int i = tbUtilisateur.getSelectedRow();
	    // récupérer les données de l'utilisateur
	    Utilisateur unUtilisateur = lesUtilisateurs.get(i);
	    // utiliser les données du tableau ou ...
	    TableModel model = tbUtilisateur.getModel();
	    uiNom.setText(model.getValueAt(i, 0).toString());
	    uiPrenom.setText(model.getValueAt(i, 1).toString());
	    uiPseudo.setText(model.getValueAt(i, 2).toString());
	    // ... ou utiliser les données de l'utilisateur
	    uiMail.setText(unUtilisateur.getMail());
	    uiMP.setText(unUtilisateur.getMP());
	    uiPhrase.setText(unUtilisateur.getPhrase());

    }//GEN-LAST:event_tbUtilisateurMouseClicked

        private void CreerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreerMouseClicked
		// TODO add your handling code here:


        }//GEN-LAST:event_CreerMouseClicked

        private void ViderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViderMouseClicked
		// TODO add your handling code here:
		tbUtilisateur.getSelectionModel().clearSelection();
		message.setText("");
		viderSaisie();
        }//GEN-LAST:event_ViderMouseClicked

        private void QuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterMouseClicked
		// TODO add your handling code here:
		System.exit(0);
        }//GEN-LAST:event_QuitterMouseClicked

        private void uiMPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_uiMPCaretUpdate
		// TODO add your handling code here:
		String pass = uiMP.getText().trim();
		BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(BCryptPasswordEncoder.BCryptVersion.$2B, 12);
		String phrase = encoder.encode(pass);
        }//GEN-LAST:event_uiMPCaretUpdate

        private void MailerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MailerMouseClicked
		// TODO add your handling code here:
		Mail courriel = new Mail(uiMail.getText());
		courriel.setVisible(true);
        }//GEN-LAST:event_MailerMouseClicked

        private void AuSujetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AuSujetMouseClicked
		// TODO add your handling code here:
		AuSujet auSujet = new AuSujet();
		auSujet.setVisible(true);
        }//GEN-LAST:event_AuSujetMouseClicked

        private void AideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AideMouseClicked
		// TODO add your handling code here:
        }//GEN-LAST:event_AideMouseClicked

        private void ParametreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParametreMouseClicked
		// TODO add your handling code here:
        }//GEN-LAST:event_ParametreMouseClicked

        private void ModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierMouseClicked
		// TODO add your handling code here:

		// mise à jour de la liste
		int i = tbUtilisateur.getSelectedRow();
		if (i < 0) {
			alert("Aucune donnée n'est selectionnée en modification ; veuillez choisir un utilisateur.");
			return;
		}
		Utilisateur unUtilisateur = lesUtilisateurs.get(i);
		if (!unUtilisateur.getPseudo().equals(uiPseudo.getText().strip())) {
			alert("Vous ne pouvez pas modifier le pseudo de l'utilisateur (creez en un autre puis supprimez l'ancien). ("
			    + unUtilisateur.getPseudo() + "/" + uiPseudo.getText().strip() + ")");
			return;
		}
		// MàJ les données de l'objet utilisateur
		unUtilisateur.setNom(uiNom.getText().strip());
		unUtilisateur.setPrenom(uiPrenom.getText().strip());
		unUtilisateur.setMail(uiMail.getText().strip());
		unUtilisateur.setMP(uiMP.getText().strip());
		unUtilisateur.setPhrase(uiMail.getText().strip());
		// MàJ des données du tableau
		TableModel model = tbUtilisateur.getModel();
		model.setValueAt(uiNom.getText(), i, 0);
		model.setValueAt(uiPrenom.getText(), i, 1);
		// mise à jour de la bd
		ouvrirDB();
		try {
			String sql = "UPDATE `utilisateur`SET ut_nom='" + unUtilisateur.getNom() + "',ut_prenom='" + unUtilisateur.getPrenom()
			    + "',ut_mail='" + unUtilisateur.getMail() + "',ut_mp='" + unUtilisateur.getMP() + "',ut_phrase='" + unUtilisateur.getPhrase()
			    + "' WHERE ut_Pseudo='" + unUtilisateur.getPseudo() + "'";
			st.execute(sql);
		} catch (SQLException ex) {
			Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
		}
		fermerDB();
		alert("L'utilisateur "+unUtilisateur.getPseudo()+" a été modifié.");
        }//GEN-LAST:event_ModifierMouseClicked

	// methode pour afficher un message
	public void alert(String msg) {
		JOptionPane.showMessageDialog(rootPane, msg);
		message.setForeground(new java.awt.Color(51, 102, 0));
		message.setText(msg);
	}

	// methode  to show an error alert
	public void alert(String msg, String titre) {
		JOptionPane.showMessageDialog(rootPane, msg, titre, JOptionPane.ERROR_MESSAGE);
		message.setForeground(new java.awt.Color(204, 0, 51));
		message.setText(msg);
	}

	//method to save user to the db
	public void saveUser(String utNom, String utPrenom, String pseudo) {
		ouvrirDB();
		try {
			String sql = "INSERT INTO `utilisateur`(`ut_Nom`, `ut_Prenom`, `ut_pseudo`) "
			    + "VALUES ('" + utNom + "','" + utPrenom + "','" + pseudo + "')";
			st.execute(sql);
		} catch (SQLException ex) {
			Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	//update the db
	public void update(String utNom, String utPrenom, String id) {
		ouvrirDB();
		try {
			String sql = "UPDATE `utilisateur`SET utNom='" + utNom + "',utPrenom='" + utPrenom + "'WHERE id_number='" + id + "'";
			st.execute(sql);
		} catch (SQLException ex) {
			Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	//delete details in the db
	public void delete(String id) {
		ouvrirDB();
		try {
			String sql = "DELETE FROM `utilisateur` WHERE id_number='" + id + "'";
			st.execute(sql);
		} catch (SQLException ex) {
			Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	// methode pour vider les champs de texte de l'écran
	private void viderSaisie() {
		uiNom.setText("");
		uiPrenom.setText("");
		uiPseudo.setText("");
		uiMail.setText("");
		uiMP.setText("");
		uiPhrase.setText("");
	}

	// ouvrir la connexion à la base de donnée et creer l'espace d'échange (statement)
	public void ouvrirDB() {
		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cryptage", "mysql", "azerty");
			st = con.createStatement();
		} catch (ClassNotFoundException | SQLException ex) {
			Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	// ouvrir la connexion à la base de donnée et creer l'espace d'échange (statement)
	public void fermerDB() {
		try {
			con.close();
			st.close();
		} catch (SQLException ex) {
			Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/*try {
            On les arrête pour éviter de prendre de la mémoire
            tab_result.close();
            lie_connect.close();
            dcl_connect.close();
        } catch (SQLException ex) {
            erreur = true;
            System.out.printf("Erreur fermeture base de donnee --> " + ex + "\n");
        }*/
	// chargerLesUtilisateurs 
	private void chargerLesUtilisateurs() {
		lesUtilisateurs.clear();
		ouvrirDB();
		try {
			String sql = "select * from utilisateur";
			ResultSet resultatSQL = st.executeQuery(sql);
			while (resultatSQL.next()) {
				Utilisateur unUtilisateur = new Utilisateur(resultatSQL.getString("ut_Nom"), resultatSQL.getString("ut_Prenom"),
				    resultatSQL.getString("ut_pseudo"), resultatSQL.getString("ut_mail"), resultatSQL.getString("ut_mp"),
				    resultatSQL.getString("ut_phrase"));
				lesUtilisateurs.add(unUtilisateur);
			}
			DefaultTableModel uiTable = (DefaultTableModel) tbUtilisateur.getModel();
			for (Utilisateur unUtilisateur : lesUtilisateurs) {

				Object[] row = new Object[3];
				row[0] = unUtilisateur.getNom();
				row[1] = unUtilisateur.getPrenom();
				row[2] = unUtilisateur.getPseudo();

				uiTable.addRow(row);
			}

		} catch (SQLException ex) {
			Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
		}
		fermerDB();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new Crud().setVisible(true);
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton Aide;
        private javax.swing.JButton AuSujet;
        private javax.swing.JButton Creer;
        private javax.swing.JLabel Entete;
        private javax.swing.JButton Mailer;
        private javax.swing.JButton Modifier;
        private javax.swing.JButton Parametre;
        private javax.swing.JButton Quitter;
        private javax.swing.JButton Supprimer;
        private javax.swing.JButton Vider;
        private javax.swing.JLabel jLabelMP;
        private javax.swing.JLabel jLabelMail;
        private javax.swing.JLabel jLabelNom;
        private javax.swing.JLabel jLabelPrenom;
        private javax.swing.JLabel jLabelPseudo;
        private javax.swing.JPanel jPanelBt;
        private javax.swing.JPanel jPanelSaisie;
        private javax.swing.JLabel message;
        private javax.swing.JScrollPane tbScrollPane;
        private javax.swing.JTable tbUtilisateur;
        private javax.swing.JLabel uiBackground;
        private javax.swing.JTextField uiMP;
        private javax.swing.JTextField uiMail;
        private javax.swing.JTextField uiNom;
        private javax.swing.JLabel uiPhrase;
        private javax.swing.JTextField uiPrenom;
        private javax.swing.JTextField uiPseudo;
        // End of variables declaration//GEN-END:variables
}
